name: ParticleAPI
main: me.raulsmail.particle.Main
version: ${project.version}
author: raulsmail
website: https://github.com/raulsmartin/RandomPlugins
commands:
  particleapi:
    usage: /particleapi
    description: Main ParticleAPI command
    aliases: [pa, particles]